# Generated by Django 2.0.1 on 2018-01-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(verbose_name='date published')),
                ('supported', models.BooleanField(default=False)),
            ],
        ),
    ]
