# Generated by Django 2.0.2 on 2018-02-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('added_date', models.DateField(verbose_name='date published')),
                ('supported', models.BooleanField(default=False)),
                ('grid_shape', models.TextField(default='', max_length=600)),
                ('grid_data', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('empty_seats', models.IntegerField(default=0)),
                ('two_empty_seats', models.IntegerField(default=0)),
                ('largest_empty_seats', models.IntegerField(default=0)),
                ('lat', models.DecimalField(decimal_places=7, default=100.0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=100.0, max_digits=10)),
                ('pc_title', models.CharField(default='', max_length=20)),
                ('pc_subtitle', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=60)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('phone_address', models.CharField(default='', max_length=20)),
                ('pc_specs', models.CharField(default='', max_length=100)),
                ('owners_words', models.CharField(default='', max_length=100)),
                ('total_seats', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImageGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200, unique=True)),
                ('grid_corners', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('grid_cell_locations', models.TextField(blank=True, default='', null=True)),
                ('base_grid', models.TextField(blank=True, default='', null=True)),
                ('anchor_image', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('r', models.IntegerField(blank=True, default=0, null=True)),
                ('g', models.IntegerField(blank=True, default=0, null=True)),
                ('b', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
