# Generated by Django 2.0.1 on 2018-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='added_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
