# Generated by Django 2.0.1 on 2018-01-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0002_auto_20180105_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grid_shape',
            field=models.CharField(default='', max_length=300),
        ),
    ]
