# Generated by Django 2.0.1 on 2018-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0003_profile_grid_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grid_shape',
            field=models.TextField(default='', max_length=300),
        ),
    ]
