# Generated by Django 2.0.1 on 2018-01-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0005_auto_20180121_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
