# Generated by Django 2.0.1 on 2018-01-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0006_auto_20180121_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
    ]
