# Generated by Django 2.0.1 on 2018-02-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0007_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='owners_words',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pc_specs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pc_subtitle',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='pc_title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_seats',
            field=models.CharField(default='', max_length=10),
        ),
    ]
