# Generated by Django 2.0.1 on 2018-02-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0008_auto_20180202_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grid_data',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grid_shape',
            field=models.TextField(default='', max_length=600),
        ),
    ]
