# Generated by Django 2.0.1 on 2018-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0010_auto_20180202_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImageGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200, unique=True)),
                ('grid_corners', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('grid_cell_locations', models.TextField(blank=True, default='', null=True)),
                ('base_grid', models.TextField(blank=True, default='', null=True)),
                ('anchor_image', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('r', models.IntegerField(blank=True, default=0, null=True)),
                ('g', models.IntegerField(blank=True, default=0, null=True)),
                ('b', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='grid_data',
            field=models.TextField(blank=True, default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
