# Generated by Django 2.0.1 on 2018-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_profile', '0011_auto_20180203_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empty_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='largest_empty_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_empty_seats',
            field=models.IntegerField(default=0),
        ),
    ]
